### ISSUE TITLE
main.py逻辑判断有误

### ISSUE THREAD

**Issue by Nyuudoukumo** [shilapi/DGLAB-CS2#1]
https://github.com/shilapi/DGLAB-CS2/blob/4e1aa98daffd55240325d78ca080d0ead594d6c7/main.py#L118C9-L118C65
118行的判断如果keep_strength_while_not_injured设置为了false的话即使掉血也不会增加强度，应该把'elif'直接改成'else'

**Comment by shilapi** [comment]
fixed
