### ISSUE TITLE
代码使用许可证问题 Code licenses issue

### ISSUE THREAD

**Issue by MiRinChan** [shilapi/DGLAB-CS2#2]
想问一下作者有准备许可此代码给其他人使用或者修改吗？我想要对代码做些许修改支持郊狼3.0
~~btw DGLAB-python-driver 好像也是您写的~~

**Comment by shilapi** [comment]
dglab 3.0的适配其实已经写完了（
但我一直没做代码优化，所以没commit
今天晚上就更

**Comment by MiRinChan** [comment]
草 好的

**Comment by shilapi** [comment]
Updated now. See https://github.com/shilapi/DGLAB-CS2/releases/tag/1.2

**Comment by MiRinChan** [comment]
> Updated now. See https://github.com/shilapi/DGLAB-CS2/releases/tag/1.2

btw 我不是 Windows 系统，可以直接运行 main.py 吗

**Comment by shilapi** [comment]
> > Updated now. See https://github.com/shilapi/DGLAB-CS2/releases/tag/1.2
> 
> 
> 
> btw 我不是 Windows 系统，可以直接运行 main.py 吗

可以的，记得安装requirement
以及Windows以外的平台我没有测试过，可能有bug，欢迎pr/更多issue
